### ISSUE TITLE
Documentation in readme

### ISSUE THREAD

**Issue by marnovo** [src-d/blog#102]
Add documentation in the `README.md` on how to:
  - Write a new blog post
  - Preview blog posts locally
  - Deploy blog posts in production
  - Add/edit authors

**Comment by vmarkovtsev** [comment]
Copied from Sergio:

Deployment:
==========

The process is quite similar to the one used [to deploy the Landing](LANDING.md)

## Production

[Production blog](http://blog.sourced.tech)

1. Push a new commit with the new code and wait for [travis-ci.org/src-d/blog](https://travis-ci.org/src-d/blog) to finish the build and provide the new image url (that will have the format: `quay.io/srcd/blog:${HASH_COMMIT}`).
2. From [cloud.google.com/live-srcd-host](https://console.cloud.google.com/compute/instancesDetail/zones/us-central1-c/instances/blog-sourced-tech), click on SSH button to open a connection into the machine.
3. From the shell, you will have to pull the new docker image, drop the old (and already stopped) blog container, rename the current/running blog container, stop it, run a new one with the just downloaded image using the same name used by the past blog container.

   The process is as follows:

Pull the created docker image
```
sudo su #docker commands must be ran as root
HASH_COMMIT='260d4fe' # seven-digit-hash-commit as said by github
docker pull quay.io/srcd/blog:${HASH_COMMIT}
```

At this point, you should see the downloaded image doing:
```
docker images
```

In order to guess which containers will be affected, and which ones are running or stopped, run the following command
```
docker ps -a
```

Now the old container will be removed (already stopped since the last deploy). Once you remove it, there will be no quick rollback to that OLD version.
Once you remove the "old" one, rename the current running container to a new "-old" name (for further rollbacks)
```
docker rm blog-old
docker rename blog blog-old 
```

Stop the current container -> Blog is DOWN -> run the new container -> Blog is UP
```
docker stop blog-old && \
docker run --restart always -d -p 80:80 -p 443:443 --name blog quay.io/srcd/blog:${HASH_COMMIT}
```

If you run `docker ps` you will see the running container has a new image, matching the downloaded image.

Cross your fingers, and press F5 :)

**Comment by marnovo** [comment]
Still missing documentation for the repo… Will create an issue in the backlog.

**Comment by marnovo** [comment]
Issue created: https://github.com/src-d/backlog/issues/1058

**Comment by dpordomingo** [comment]
Consider the following:
https://github.com/src-d/blog/issues/143

**Comment by dpordomingo** [comment]
@vmarkovtsev Due to the other issues that supersedes this one, please close this issue

**Comment by vmarkovtsev** [comment]
@marnovo Given your blessing
